//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InjuredPixels.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InjuredPixels.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurelitec\InjuredPixels.
        /// </summary>
        internal static string AppDataPath {
            get {
                return ResourceManager.GetString("AppDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlwaysOnTop.
        /// </summary>
        internal static string ConfigAlwaysOnTop {
            get {
                return ResourceManager.GetString("ConfigAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorIndex.
        /// </summary>
        internal static string ConfigColorIndex {
            get {
                return ResourceManager.GetString("ConfigColorIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomColor.
        /// </summary>
        internal static string ConfigCustomColor {
            get {
                return ResourceManager.GetString("ConfigCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ConfigGeneral {
            get {
                return ResourceManager.GetString("ConfigGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InjuredPixels.ini.
        /// </summary>
        internal static string ConfigName {
            get {
                return ResourceManager.GetString("ConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowMouseCursor.
        /// </summary>
        internal static string ConfigShowMouseCursor {
            get {
                return ResourceManager.GetString("ConfigShowMouseCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TouchMode.
        /// </summary>
        internal static string ConfigTouchMode {
            get {
                return ResourceManager.GetString("ConfigTouchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading configuration.
        /// </summary>
        internal static string LogErrorLoadConfig {
            get {
                return ResourceManager.GetString("LogErrorLoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving configuration.
        /// </summary>
        internal static string LogErrorSaveConfig {
            get {
                return ResourceManager.GetString("LogErrorSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} - {2}.
        /// </summary>
        internal static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RadioCheckIconBlack {
            get {
                object obj = ResourceManager.GetObject("RadioCheckIconBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RadioCheckIconWhite {
            get {
                object obj = ResourceManager.GetObject("RadioCheckIconWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Monitors.
        /// </summary>
        internal static string UiAllMonitorsMenu {
            get {
                return ResourceManager.GetString("UiAllMonitorsMenu", resourceCulture);
            }
        }
    }
}
